# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - npm install
      - git add .
      - git commit
      - npm run build
      - npm run dev
    silent: false
